export default [
	{
		id: 1,
		patientName: "John Smith",
		appointmentType: "General Checkup",
		status: "Scheduled",
		date: "2024-03-20",
		time: "14:30",
		duration: "30",
		doctorName: "Dr. Sarah Wilson",
	},
	{
		id: 2,
		patientName: "Maria Silva",
		appointmentType: "Cardiology",
		status: "Completed",
		date: "2024-03-18",
		time: "09:00",
		duration: "45",
		doctorName: "Dr. Carlos Mendes",
	},
	{
		id: 3,
		patientName: "Pedro Santos",
		appointmentType: "Dermatology",
		status: "Cancelled",
		date: "2024-03-19",
		time: "16:00",
		duration: "30",
		doctorName: "Dr. Ana Costa",
	},
	{
		id: 4,
		patientName: "Ana Oliveira",
		appointmentType: "Pediatrics",
		status: "Scheduled",
		date: "2024-03-21",
		time: "10:15",
		duration: "20",
		doctorName: "Dr. Roberto Lima",
	},
	{
		id: 5,
		patientName: "José Ferreira",
		appointmentType: "Orthopedics",
		status: "Completed",
		date: "2024-03-17",
		time: "13:45",
		duration: "60",
		doctorName: "Dr. Lucia Rodrigues",
	},
	{
		id: 6,
		patientName: "Carla Souza",
		appointmentType: "Gynecology",
		status: "Scheduled",
		date: "2024-03-22",
		time: "11:30",
		duration: "40",
		doctorName: "Dr. Patricia Alves",
	},
	{
		id: 7,
		patientName: "Roberto Costa",
		appointmentType: "Neurology",
		status: "Pending",
		date: "2024-03-23",
		time: "15:00",
		duration: "50",
		doctorName: "Dr. Fernando Dias",
	},
	{
		id: 8,
		patientName: "Lucia Martins",
		appointmentType: "Ophthalmology",
		status: "Cancelled",
		date: "2024-03-16",
		time: "08:30",
		duration: "25",
		doctorName: "Dr. Marcos Silva",
	},
	{
		id: 9,
		patientName: "Bruno Pereira",
		appointmentType: "Psychiatry",
		status: "Scheduled",
		date: "2024-03-24",
		time: "17:30",
		duration: "60",
		doctorName: "Dr. Claudia Nunes",
	},
	{
		id: 10,
		patientName: "Fernanda Lima",
		appointmentType: "General Checkup",
		status: "Completed",
		date: "2024-03-15",
		time: "12:00",
		duration: "30",
		doctorName: "Dr. Sarah Wilson",
	}
];
